### ISSUE TITLE
Uglification failed

### ISSUE THREAD

**Issue by szyjava** [aui/tmodjs#92]
{ [Error: Uglification failed.
Unexpected token: punc ()). 
Line 177 in e:/workspace/OA/build/template.js
]
  origError: 
   { message: 'Unexpected token: punc ())',
     line: 177,
     col: 12,
     pos: 4060,
     stack: 'Error\n    at new JS_Parse_Error (e:\\workspace\\OA\\node_modules\\tmodjs\\node_modules\\uglify-js\\lib\\parse.js:196:18)\n    at js_error (e:\\workspace\\OA\\node_modules\\tmodjs\\node_modules\\uglify-js\\lib\\parse.js:204:11)\n    at croak (e:\\workspace\\OA\\node_modules\\tmodjs\\node_modules\\uglify-js\\lib\\parse.js:640:41)\n    at token_error (e:\\workspace\\OA\\node_modules\\tmodjs\\node_modules\\uglify-js\\lib\\parse.js:644:9)\n    at unexpected (e:\\workspace\\OA\\node_modules\\tmodjs\\node_modules\\uglify-js\\lib\\parse.js:650:9)\n    at e:\\workspace\\OA\\node_modules\\tmodjs\\node_modules\\uglify-js\\lib\\parse.js:730:17\n    at e:\\workspace\\OA\\node_modules\\tmodjs\\node_modules\\uglify-js\\lib\\parse.js:683:24\n    at block_ (e:\\workspace\\OA\\node_modules\\tmodjs\\node_modules\\uglify-js\\lib\\parse.js:944:20)\n    at e:\\workspace\\OA\\node_modules\\tmodjs\\node_modules\\uglify-js\\lib\\parse.js:917:25\n    at function_ (e:\\workspace\\OA\\node_modules\\tmodjs\\node_modules\\uglify-js\\lib\\parse.js:922:15)' } }

为什么一直是压缩出错啦 求解决

**Comment by kingyu** [comment]
同样有这个问题，以前都是好好的，今天编译就出错了，更新node.js后就出问题了

现在node -v 版本v4.2.3

**Comment by zcoding** [comment]
据说作者已经不维护了
